name: List Data Files
on: [push]
jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".yml"
          
  Test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Output results
        run: |
          echo ${{ matrix.paths }}

      - name: Overwrite File
        uses: "DamianReeves/write-file-action@master"
        with:
          path: data_file_list.txt
          write-mode: overwrite
          contents: |
            ${{ needs.list-files.outputs.paths }}
            
      - name: Push Commit
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Data File List Updated'
          author_email: actions@github.com
          author_name: GitHub Actions 🤖 <actions@github.com>
