name: List Data Files
on: [push]
jobs:
  list-data-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-data-files.outputs.paths }}
    steps:
      - name: List Data Files
        id: list-data-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "data"
          ext: ".json"
          
  Test:
    needs: list-data-files
    runs-on: ubuntu-latest
    steps:
      - name: Output Results
        run: |
          echo ${{ needs.list-data-files.outputs.paths }}

      - name: Overwrite Output File
        uses: "DamianReeves/write-file-action@master"
        with:
          path: data_file_list.json
          write-mode: overwrite
          contents: |
            ${{ github.repository }}
            ${{ needs.list-data-files.outputs.paths }}
            
      - name: Push Commit
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Data File List Updated'
          author_email: actions@github.com
          author_name: GitHub Actions 🤖 <actions@github.com>
