name: List Data Files
on: [push]
jobs:
  list-data-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-data-files.outputs.paths }}
    steps:
      - name: List Data Files
        id: list-data-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "data"
          ext: ".json"
          
  Test:
    needs: list-data-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Overwrite Output File
        uses: DamianReeves/write-file-action@master
        with:
          path: dataFileList.json
          write-mode: overwrite
          contents: |
            ${{ needs.list-data-files.outputs.paths }}

      - name: Push Commit
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Data File List Updated'
          author_email: actions@github.com
          author_name: GitHub Actions 🤖 <actions@github.com>
