name: List Data Files
on: [push]
jobs:
  list:
    name: List Data Files
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch Action
        id: path_list
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "data/"
          type: ".json"

      - name: Overwrite File
        uses: "DamianReeves/write-file-action@master"
        with:
          path: data_file_list.txt
          write-mode: overwrite
          contents: |
            ${{ steps.path_list.outputs.paths }} | tr " " "\n"
            
      - name: Push Commit
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Data File List Updated'
          author_email: actions@github.com
          author_name: GitHub Actions 🤖 <actions@github.com>
